# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dac8dce1cad2a2c237d2d23d3aa6a7e2b706d8f3efc44bd4d5b37873d0fa36df2e1686de26e89d02b62daa2926ffa97b2bd6087abf6dcdf589db50e28e096001

test:
  secret_key_base: b676ee8e5e2e668cfe56006560ddf96644c9998d8097b64b3ec629cada07dd8e902b2acc317dd09142f0cfa711bae846788d3daeca1560a21ac126215f3499b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
